version: "2"
services:
  app:
    container_name: ya-server
    restart: always
    mem_limit: 300m
    memswap_limit: 1g
    env_file:
      .env
    build: .
    ports:
      - '3000:8000'
    volumes:
      - .:/home/nodejs/app
      - /home/nodejs/app/node_modules
    links:
      - mongo
  mongo:
    container_name: ya-mongo-db
    image: mongo
    volumes:
      # - ./data:/home/nodejs/data/db
      - 'mongo:/data/db'
    ports:
      - "27017:27017"
